name: HardcoreWorldReset
version: 1.0.2
main: es.servidor.hardcorereset.HardcoreWorldReset
api-version: '26.2'
description: Hardcore global con mundos nuevos de Overworld, Nether y End, contador de muertes y vida en TAB.
