name: HardcoreWorldReset
version: 1.0.0
main: es.servidor.hardcorereset.HardcoreWorldReset
api-version: '26.2'
description: Hardcore por vidas, reinicio completo de Overworld/Nether/End y marcadores.
